include_defs("buckit//DEFS")

libs = [
    LibraryRule("gflags"),
    LibraryRule("gflags_nothreads"),
]

if not buckit_use_system('gflags'):
    buckit_cpp_cmake_library(
        main_rule='gflags',
        libs=libs,
        additional_cmake_args={
            'CMAKE_BUILD_TYPE': 'Release',
            'BUILD_TESTING': 'ON',
            'BUILD_SHARED_LIBS': 'OFF',
        },
        build_extra_with_use_shared_libs=True,
    )

else:
    buckit_system_library(
        main_rule='gflags',
        libs=libs,
        use_pkg_config=False,
    )
