load("@fbcode_macros//build_defs:python_library.bzl", "python_library")
load("//fs_image/buck:image.bzl", "image")

python_library(
    name = "coverage_test_helper",
    srcs = ["coverage_test_helper.py"],
    base_module = "",
)

image.python_unittest(
    name = "test-image-python-unittest",
    srcs = ["test_image_python_unittest.py"],
    layer = "//fs_image/compiler/tests:only-for-tests-read-only-host-clone",
    needed_coverage = [(100, ":coverage_test_helper")],
    deps = [":coverage_test_helper"],
)
