load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

python_library(
    name = "cxx_sources",
    srcs = [
        "cxx_sources.py",
    ],
)

python_library(
    name = "rule",
    srcs = [
        "rule.py",
    ],
    # Buckification macros must be runnable from source tree and so *cannot*
    # have any deps.
    deps = [],
    external_deps = [],
)

python_library(
    name = "constants",
    srcs = {
        "constants.bzl": "constants.py",
    },
    # Buckification macros must be runnable from source tree and so *cannot*
    # have any deps.
    deps = [],
    external_deps = [],
)

python_library(
    name = "target",
    srcs = [
        "target.py",
    ],
    # Buckification macros must be runnable from source tree and so *cannot*
    # have any deps.
    deps = [],
    external_deps = [],
)
