load(
    "@fbcode_macros//tests:skylark_integration_test.bzl",
    "skylark_integration_tests",
)

TESTS = [
    "allocators_test",
    "build_info_test",
    "common_paths_test",
    "copy_rule_test",
    "core_tools_test",
    "cpp_common_test",
    "cpp_flags_test",
    "cuda_test",
    "haskell_common_test",
    "label_utils_test",
    "lua_common_test",
    "modules_test",
    "python_typing_test",
    "python_versioning_test",
    "shell_test",
    "src_and_dep_helpers_test",
    "string_macros_test",
    "target_utils_test",
    "third_party_test",
    "visibility_test",
]

skylark_integration_tests(TESTS)
