include_defs("buckit//DEFS")

libs = [
    LibraryRule(
        "unwind",
        ["xz//xz:lzma"],
    ),
]

if not buckit_use_system('unwind'):
    buckit_cpp_autoconf_library(
        main_rule='unwind',
        libs=libs,
    )
else:
    buckit_system_library(
        main_rule='unwind',
        libs=libs,
        use_pkg_config=False,
    )
