include_defs('buckit//DEFS')

libs = []

if not buckit_use_system('patchelf'):
    buckit_cpp_autoconf_library(
        main_rule='patchelf',
        libs=libs,
        build_rule_visibility=['PUBLIC'],
    )
else:
    buckit_system_library(
        main_rule='patchelf',
        libs=libs,
        use_pkg_config=False,
        binaries=[('patchelf', 'patchelf')],
    )
