# The test needs at least two rules so we can test dependencies.
thrift_library(
    name = "parent",
    languages = [
        "py",
        "thriftdoc-py",
    ],
    py_base_module = "",
    thrift_srcs = {"parent.thrift": []},
    deps = [":leaves"],
)

# This rule has two `.thrift` files to ensure multi-file libraries work.
thrift_library(
    name = "leaves",
    languages = [
        "py",
        "thriftdoc-py",
    ],
    py_base_module = "",
    thrift_srcs = {
        "leaf1.thrift": [],
        "leaf2.thrift": [],
    },
)

# We need a binary to materialize the above libraries. As a side effect, we
# get to check that basic validation works.
python_unittest(
    name = "test-thriftdoc-py",
    srcs = ["test_thriftdoc.py"],
    deps = [
        ":parent-py",
        ":parent-thriftdoc-py",
        "//tupperware/thriftdoc/validator:validate_thriftdoc",
    ],
)
