load("//fs_image/buck:defs.bzl", "fake_macro_library")

fake_macro_library(
    name = "mkdir",
    srcs = ["mkdir.bzl"],
    deps = [
        "//fs_image/buck:add_stat_options",
        "//fs_image/buck:image_feature",
    ],
)
