load("@fbsource//tools/build_defs:fb_native_wrapper.bzl", "fb_native")
load(
    "@fbcode_macros//tests:skylark_integration_test.bzl",
    "skylark_integration_test",
    "targets_to_resource_paths",
)

BUILD_DEFS = [
    "fbcode_macros//build_defs:auto_headers.bzl",
    "fbcode_macros//build_defs:auto_pch_blacklist.bzl",
    "fbcode_macros//build_defs:antlr3_srcs.bzl",
    "fbcode_macros//build_defs:allocators.bzl",
    "fbcode_macros//build_defs:allocator_targets.bzl",
    "fbcode_macros//build_defs:build_info.bzl",
    "fbcode_macros//build_defs:build_mode.bzl",
    "fbcode_macros//build_defs:build_mode_overrides.bzl",
    "fbcode_macros//build_defs:common_paths.bzl",
    "fbcode_macros//build_defs:compiler.bzl",
    "fbcode_macros//build_defs:config.bzl",
    "fbcode_macros//build_defs:coverage.bzl",
    "fbcode_macros//build_defs:core_tools.bzl",
    "fbcode_macros//build_defs:cpp_benchmark.bzl",
    "fbcode_macros//build_defs:cpp_binary.bzl",
    "fbcode_macros//build_defs:cpp_common.bzl",
    "fbcode_macros//build_defs:cpp_flags.bzl",
    "fbcode_macros//build_defs:cpp_java_extension.bzl",
    "fbcode_macros//build_defs:cpp_library.bzl",
    "fbcode_macros//build_defs:cpp_lua_main_module.bzl",
    "fbcode_macros//build_defs:cpp_lua_extension.bzl",
    "fbcode_macros//build_defs:cpp_node_extension.bzl",
    "fbcode_macros//build_defs:cpp_python_extension.bzl",
    "fbcode_macros//build_defs:cpp_precompiled_header.bzl",
    "fbcode_macros//build_defs:cpp_unittest.bzl",
    "fbcode_macros//build_defs:cuda.bzl",
    "fbcode_macros//build_defs:create_build_mode.bzl",
    "fbcode_macros//build_defs:cpp_library_external.bzl",
    "fbcode_macros//build_defs:default_platform.bzl",
    "fbcode_macros//build_defs:d_library_external.bzl",
    "fbcode_macros//build_defs:custom_rule.bzl",
    "fbcode_macros//build_defs:dewey_artifact.bzl",
    "fbcode_macros//build_defs:export_files.bzl",
    "fbcode_macros//build_defs:global_compiler.bzl",
    "fbcode_macros//build_defs:haskell_common.bzl",
    "fbcode_macros//build_defs:haskell_external_library.bzl",
    "fbcode_macros//build_defs:lex.bzl",
    "fbcode_macros//build_defs:go_external_library.bzl",
    "fbcode_macros//build_defs:java_binary.bzl",
    "fbcode_macros//build_defs:java_common.bzl",
    "fbcode_macros//build_defs:java_library.bzl",
    "fbcode_macros//build_defs:java_test.bzl",
    "fbcode_macros//build_defs:java_shaded_jar.bzl",
    "fbcode_macros//build_defs:js_common.bzl",
    "fbcode_macros//build_defs:js_executable.bzl",
    "fbcode_macros//build_defs:js_node_module_external.bzl",
    "fbcode_macros//build_defs:js_npm_module.bzl",
    "fbcode_macros//build_defs:label_utils.bzl",
    "fbcode_macros//build_defs:lua_common.bzl",
    "fbcode_macros//build_defs:missing_tp2_project.bzl",
    "fbcode_macros//build_defs:modules.bzl",
    "fbcode_macros//build_defs:native_rules.bzl",
    "fbcode_macros//build_defs:ocaml_external_library.bzl",
    "fbcode_macros//build_defs:paths_config.bzl",
    "fbcode_macros//build_defs:platform_utils.bzl",
    "fbcode_macros//build_defs:platform_overrides.bzl",
    "fbcode_macros//build_defs:python_typing.bzl",
    "fbcode_macros//build_defs:python_versioning.bzl",
    "fbcode_macros//build_defs:prebuilt_jar.bzl",
    "fbcode_macros//build_defs:rust_external_library.bzl",
    "fbcode_macros//build_defs:sanitizers.bzl",
    "fbcode_macros//build_defs:scala_library.bzl",
    "fbcode_macros//build_defs:scala_test.bzl",
    "fbcode_macros//build_defs:shell.bzl",
    "fbcode_macros//build_defs:src_and_dep_helpers.bzl",
    "fbcode_macros//build_defs:string_macros.bzl",
    "fbcode_macros//build_defs:rule_target_types.bzl",
    "fbcode_macros//build_defs:target_utils.bzl",
    "fbcode_macros//build_defs:third_party.bzl",
    "fbcode_macros//build_defs:third_party_config.bzl",
    "fbcode_macros//build_defs:visibility.bzl",
    "fbcode_macros//build_defs:visibility_exceptions.bzl",
    "fbcode_macros//build_defs:yacc.bzl",
    "fbcode_macros//build_defs/config:read_configs.bzl",
    "fbcode_macros//tools:get_build_mode.py",
    "fbcode_macros//tools:get_platform.py",
    "fbcode_macros//tools:BUCK",
    "bazel_skylib//:lib.bzl",
    "bazel_skylib//lib:collections.bzl",
    "bazel_skylib//lib:dicts.bzl",
    "bazel_skylib//lib:new_sets.bzl",
    "bazel_skylib//lib:partial.bzl",
    "bazel_skylib//lib:paths.bzl",
    "bazel_skylib//lib:selects.bzl",
    "bazel_skylib//lib:sets.bzl",
    "bazel_skylib//lib:shell.bzl",
    "bazel_skylib//lib:structs.bzl",
    "bazel_skylib//lib:types.bzl",
    "bazel_skylib//lib:versions.bzl",
    "xplat//tools/build_defs:type_defs.bzl",
    "fbsource//tools/build_defs:buckconfig.bzl",
    "fbsource//tools/build_defs:copy_defs.bzl",
    "fbsource//tools/build_defs:fb_native_wrapper.bzl",
    "fbsource//tools/build_defs:sanitizers.bzl",
    "fbsource//tools/build_defs:translate_to_fbsource_paths.bzl",
    "fbsource//tools/build_defs:type_defs.bzl",
]

UTIL_DEFS = targets_to_resource_paths(BUILD_DEFS)

UTIL_DEFS[".buckversion"] = ":buckversion"

# This should change whenever the buck version meaningfully changes
genrule(
    name = "buckversion",
    srcs = ["fbcode_macros//:buckversion"],
    out = "buckversion",
    cmd = "buck --version | awk {'print $3'} > $OUT",
)

fb_native.python_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
    resources = UTIL_DEFS,
    visibility = ["PUBLIC"],
    deps = [
        "fbcode_macros//tests/third-party/future:future",
        "fbcode_macros//tests/third-party/setuptools:setuptools",
        "fbcode_macros//tests/third-party/six:six",
    ],
)

skylark_integration_test(
    name = "allocators_test",
    srcs = ["allocators_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "build_info_test",
    srcs = ["build_info_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "build_mode_test",
    srcs = ["build_mode_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "common_paths_test",
    srcs = ["common_paths_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "compiler_test",
    srcs = ["compiler_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "config_test",
    srcs = ["config_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "cpp_flags_test",
    srcs = ["cpp_flags_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_java_extension_test",
    srcs = ["cpp_java_extension_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_lua_extension_test",
    srcs = ["cpp_lua_extension_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_lua_main_module_test",
    srcs = ["cpp_lua_main_module_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_node_extension_test",
    srcs = ["cpp_node_extension_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_python_extension_test",
    srcs = ["cpp_python_extension_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_precompiled_header_test",
    srcs = ["cpp_precompiled_header_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_benchmark_test",
    srcs = ["cpp_benchmark_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_common_test",
    srcs = ["cpp_common_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_binary_test",
    srcs = ["cpp_binary_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_library_test",
    srcs = ["cpp_library_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "cpp_unittest_test",
    srcs = ["cpp_unittest_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "coverage_test",
    srcs = ["coverage_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "custom_rule_test",
    srcs = ["custom_rule_test.py"],
    resources = glob(["testdata/custom_rule/*"]),
)

skylark_integration_test(
    name = "core_tools_test",
    srcs = ["core_tools_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "cpp_library_external_test",
    srcs = ["cpp_library_external_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "cuda_test",
    srcs = ["cuda_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "go_external_library_test",
    srcs = ["go_external_library_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "export_files_test",
    srcs = ["export_files_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "lex_test",
    srcs = ["lex_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "haskell_external_library_test",
    srcs = ["haskell_external_library_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "js_executable_test",
    srcs = ["js_executable_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "haskell_common_test",
    srcs = ["haskell_common_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "js_node_module_external_test",
    srcs = ["js_node_module_external_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "js_npm_module_test",
    srcs = ["js_npm_module_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "label_utils_test",
    srcs = ["label_utils_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "missing_tp2_project_test",
    srcs = ["missing_tp2_project_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "modules_test",
    srcs = ["modules_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "native_rules_test",
    srcs = ["native_rules_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "ocaml_external_library_test",
    srcs = ["ocaml_external_library_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "platform_utils_test",
    srcs = ["platform_utils_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "python_typing_test",
    srcs = ["python_typing_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "python_versioning_test",
    srcs = ["python_versioning_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "rust_external_library_test",
    srcs = ["rust_external_library_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "sanitizers_test",
    srcs = ["sanitizers_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "shell_test",
    srcs = ["shell_test.py"],
)

skylark_integration_test(
    name = "src_and_dep_helpers_test",
    srcs = ["src_and_dep_helpers_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "string_macros_test",
    srcs = ["string_macros_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)

skylark_integration_test(
    name = "target_utils_test",
    srcs = ["target_utils_test.py"],
)

skylark_integration_test(
    name = "third_party_test",
    srcs = ["third_party_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "third_party_config_test",
    srcs = ["third_party_config_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "utils_test",
    srcs = ["utils_test.py"],
    resources = ["testdata/utils_test/sample.txt"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "visibility_test",
    srcs = ["visibility_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "yacc_test",
    srcs = ["yacc_test.py"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "lua_common_test",
    srcs = ["lua_common_test.py"],
    deps = [
        "fbcode_macros//tests/facebook:utils",
        ":utils",
    ],
)
