load(
    "@fbcode_macros//tests:skylark_integration_test.bzl",
    "skylark_integration_test",
    "target_to_resource_path",
    "targets_to_resource_paths",
)

BUILD_DEFS = [
    "fbcode_macros//build_defs:config.bzl",
    "fbcode_macros//build_defs/config:read_configs.bzl",
]

UTIL_DEFS = targets_to_resource_paths(BUILD_DEFS)

python_library(
    name = "utils",
    srcs = [
        "utils.py",
    ],
    resources = UTIL_DEFS,
    visibility = ["PUBLIC"],
    deps = [
        "fbcode_macros//tests/third-party/future:future",
        "fbcode_macros//tests/third-party/six:six",
    ],
)

skylark_integration_test(
    name = "utils_test",
    srcs = ["utils_test.py"],
    resources = ["testdata/utils_test/sample.txt"],
    deps = [":utils"],
)

skylark_integration_test(
    name = "config_test",
    srcs = ["config_test.py"],
    deps = [":utils"],
)
