# This file is intended to become a collection of utility features commonly
# used in constructing images.
load("//fs_image/buck:image.bzl", "image")

# To remove a path in this feature it should match these criteria:
#  - its absence should makes the running image operate no less correctly
#    than before,
#  - the image does not become less human-understandable once it's gone, or
#    the considerable space savings justifies the loss of debuggability.
image.feature(
    name = "rpm_cleanup",
    features = [
        image.remove(
            "/var/cache/yum",
            must_exist = False,
        ),
    ],
)

# Remove filesystem items that should ONLY be created at runtime, but might
# have leaked into an image at build-time due to bugs.  If an image is
# constructed only using supported `image.feature` and `image.layer`
# operations, this clean-up should not be be necessary.  However, this can
# be useful for assimilating foreign-built images.
image.feature(
    name = "build_artifact_cleanup",
    # Since we generally build images for containers, we should make sure
    # that they do NOT contain a machine-id.  The concern is that the fixed
    # machine ID would leak into other filesystem artifacts, which would
    # then break when the machine-id inevitably gets changed at run-time.
    features = [
        image.remove(
            "/etc/machine-id",
            must_exist = False,
        ),
        image.install_data(
            "empty-machine-id",
            "/etc/machine-id",
        ),
    ],
)
