load("@fbcode_macros//build_defs:java_library.bzl", "java_library")
load("@fbcode_macros//build_defs:python_library.bzl", "python_library")

# A dummy rule used by `tools/build/test/TARGETS` to make sure changes to any
# of these files trigger thoses tests on diffs.
python_library(
    name = "infra_macros",
    srcs = glob(["macro_lib/**/*.py"]),
    resources = [
        "macros.bzl",
    ],
    # Buckification macros must be runnable from source tree and so *cannot*
    # have any deps.
    deps = [],
    external_deps = [],
)

# A similar dummy rule used by the Java tests.
java_library(
    name = "infra_macros_java",
    java_versions = [
        "11",
        "8",
    ],
    resources = (
        glob([
            "macro_lib/**/*.py",
        ]) + [
            "fbcode_macros//build_defs:all_bzl_files",
            "macros.bzl",
        ]
    ),
    resources_root = ".",
)
