load("@fbcode_macros//build_defs:export_files.bzl", "export_files")

files = glob(["*.bzl"])

export_files(
    files,
)

zip_file(
    name = "all_bzl_files",
    srcs = files,
    visibility = ["PUBLIC"],
)
